### ISSUE TITLE
[Bug] Songs not playing on dubble click on songs page

### ISSUE THREAD

**Issue by Sanderstarr** [somebeaver/Cardinal-Music#1] opened 2021-06-12 14:13 UTC
When I start the app (windows 10) switch to the songs page I can doubble click on songs to play them.
But when I do that and switch between pages and go back to the songs page doubble clicking the songs doesn't work anymore.

**Comment by somebeaver** [comment] 2021-06-12 16:05
Confirmed the bug on my end.

In the mean time, Ctrl+clicking the Songs link to hard refresh the view will make double click work again, but the cached scroll position will be lost.

**Comment by somebeaver** [comment] 2021-06-18 19:49
Wontfix because page this table is being replaced with a better one soon.

**Closed by somebeaver** 2021-06-18 19:49 UTC
Labels: bug, good first issue, wontfix
